global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mqtt_exporter"
    static_configs:
      - targets: ["mqtt2prometheus:9641"] # Scraping metrics from the mqtt2prometheus exporter
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
